name: Publish package

on:
  push:
    branches:
      - main

jobs: 
  publish-github:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry: 'https://npm.pkg.github.com'
          scope: '@morenoalexander'
      - name: npm publish
        run: npm publish --access public
        env:
          NPM_USER_CONFIG: /home/runner/work/cra-template-serious-business/cra-template-serious-business/.npmrc
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
        
      - name: npm publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    
